### ISSUE TITLE
LINQ Query Does Not Respect JsonProperty Attribute

### ISSUE THREAD

**Issue by kspearrin** [Azure/azure-documentdb-net#68] opened 2015-10-16 23:34 UTC
Using LINQ in the SDK does not produce the correct query. See the following example:

My `User` class:

    public class User
    {
        [JsonProperty("id")]
        public string Id { get; private set; }
        [JsonProperty("type")]
        public string Type { get; private set; }

        public string Username { get; set; }

        // ....
    }

and LINQ query:

    Client.CreateDocumentQuery<User>(DatabaseUri, new FeedOptions { MaxItemCount = 1 })
        .Where(d => d.Id == "GUID").AsEnumerable();

produces the following query:

    SELECT * FROM root WHERE (root.Id = "GUID")

This finds no results because `Id` was not lowercase in the query, as specified in the `JsonProperty` attribute.

Running this query in the portal with the query explorer manually returns the expected result:

    SELECT * FROM root WHERE (root.id = "GUID")

**Comment by ryancrawcour** [comment] 2015-10-16 23:39
What version of the SDK are you using?

**Comment by kspearrin** [comment] 2015-10-16 23:40
"Microsoft.Azure.DocumentDB": "1.5.0"

**Comment by kspearrin** [comment] 2015-10-16 23:43
I also noticed this same issue when running the samples project, which used `[JsonConverter(typeof(StringEnumConverter))]` on some enums initially.

see my pull request, which just removed it as a work-around https://github.com/Azure/azure-documentdb-net/pull/63

**Comment by ryancrawcour** [comment] 2015-10-17 00:31
Can't reproduce. 

            using (var client = new DocumentClient(new Uri(endpoint), authKey))
            {
                string id = "bar";
                Document d = client.CreateDocumentAsync(UriFactory.CreateDocumentCollectionUri(dbid, collid), new Foo { Id =  id}).Result;

                var query = client.CreateDocumentQuery<Foo>(UriFactory.CreateDocumentCollectionUri(dbid, collid)).Where(f => f.Id == id);
                Console.WriteLine(query.ToString());

                Foo foo = query.AsEnumerable().FirstOrDefault();
                Console.WriteLine(foo.Id);
            }

query.ToString() produces - {"query":"SELECT * FROM root WHERE (root.id = \"boo\") "}
and the result of the object returned is as expected - "boo"

**Comment by ryancrawcour** [comment] 2015-10-17 00:33
Can you supply a repro, please

**Comment by kspearrin** [comment] 2015-10-17 01:16
This example more closely mates my real code base. Looks like it has something to do with the generics in my Repository class. My original explanation in this thread didn't include that, so that example likely works as expected.

Run this console app:

https://gist.github.com/kspearrin/d5c11170e9188029fbb3

**Comment by kspearrin** [comment] 2015-10-17 01:19
I see the issue now. It appears that `[JsonProperty("id")]` needs to be added to the IDataObject `Interface`. Adding this makes this example work.

    public interface IDataObject
    {
        [JsonProperty("id")]
        string Id { get; }
    }

Sorry about that. Thanks.

**Comment by kspearrin** [comment] 2015-10-19 13:46
`JsonConverter`, however, is still an issue. See this gist https://gist.github.com/kspearrin/ffbe164c55ef102b8595

**Comment by ryancrawcour** [comment] 2015-10-19 17:23
Yes, we are aware of the JsonConverter issues. These will be addressed in a future release.

**Closed by ryancrawcour** 2015-10-19 17:23 UTC

**Comment by ryancrawcour** [comment] 2015-10-19 17:24
Could you please x-post your JsonConverter issue as a comment on https://github.com/Azure/azure-documentdb-net/issues/55 so that we can track all JsonConverter related issues on a single issue. Thanks.
